#!/usr/bin/env python3
"""
Reset Generated Files to Placeholders

This script overwrites all generated tables and figures with placeholder content,
allowing you to demonstrate the reproduction workflow from a clean state.

Usage:
    python3 reset_to_placeholders.py [--dry-run]

To restore generated content:
    python3 final_runs/reproduce_all_thesis_assets.py
"""

import argparse
import shutil
from pathlib import Path

# Repository root
REPO_ROOT = Path(__file__).parent
FINAL_RUNS = REPO_ROOT / "final_runs"
THESIS_GENERATED = REPO_ROOT / "thesis" / "reproducible_version" / "generated"
THESIS_FIGURES_GENERATED = REPO_ROOT / "thesis" / "reproducible_version" / "Figures" / "generated"
THESIS_FIGURES = REPO_ROOT / "thesis" / "reproducible_version" / "Figures"

# Placeholder content
PLACEHOLDER_TABLE = """\
% Placeholder - run reproduce_all_thesis_assets.py to generate
\\textit{[Table: run reproduction scripts to generate]}
"""

# Special placeholder for "numbers" files that define LaTeX commands
# These commands are used inline in the thesis text, so they must be defined
NUMBERS_PLACEHOLDERS = {
    "rq3_human_validation_numbers.tex": """\
% Placeholder - run reproduce_all_thesis_assets.py to generate
\\providecommand{\\rqThreeHVN}{???}
\\providecommand{\\rqThreeHVScope}{???}
\\providecommand{\\rqThreeHVCoverage}{???}
\\providecommand{\\rqThreeHVCorrect}{???}
""",
    "rq3_enrichment_validation_numbers.tex": """\
% Placeholder - run reproduce_all_thesis_assets.py to generate
\\providecommand{\\rqThreeValThresh}{???}
\\providecommand{\\rqThreeFpPromote}{???}
\\providecommand{\\rqThreeFpPromoteCons}{???}
\\providecommand{\\rqThreeFnDiscover}{???}
\\providecommand{\\rqThreeFnDiscoverCons}{???}
\\providecommand{\\rqThreeFOne}{???}
\\providecommand{\\rqThreeFEnrich}{???}
\\providecommand{\\rqThreeFEnrichCons}{???}
\\providecommand{\\rqThreeFSystem}{???}
\\providecommand{\\rqThreeFSystemCons}{???}
\\providecommand{\\rqThreePrecOne}{???}
\\providecommand{\\rqThreeRecOne}{???}
\\providecommand{\\rqThreePrecEnrich}{???}
\\providecommand{\\rqThreeRecEnrich}{???}
\\providecommand{\\rqThreePrecSystem}{???}
\\providecommand{\\rqThreeRecSystem}{???}
""",
    "rq3_smart_trigger_numbers.tex": """\
% Placeholder - run reproduce_all_thesis_assets.py to generate
% Trigger parameters
\\providecommand{\\rqThreeTriggerThreshold}{???}
\\providecommand{\\rqThreeApplicabilityThreshold}{???}
% Triggered counts
\\providecommand{\\rqThreeFPTriggeredDR}{???}
\\providecommand{\\rqThreeFNTriggeredDR}{???}
% Calibration rates
\\providecommand{\\rqThreePFP}{???}
\\providecommand{\\rqThreePFPCI}{???}
\\providecommand{\\rqThreePFN}{???}
\\providecommand{\\rqThreePFNCI}{???}
% Original metrics
\\providecommand{\\rqThreeOrigF}{???}
\\providecommand{\\rqThreeOrigP}{???}
\\providecommand{\\rqThreeOrigR}{???}
% Scenario 1: Enriched GT (FP promotions only)
\\providecommand{\\rqThreeSTFpPromote}{???}
\\providecommand{\\rqThreeSTEnrichF}{???}
\\providecommand{\\rqThreeSTEnrichFCI}{???}
\\providecommand{\\rqThreeSTEnrichP}{???}
\\providecommand{\\rqThreeSTEnrichR}{???}
% Scenario 2: LLM+DR system (FP + FN)
\\providecommand{\\rqThreeSTFnDiscover}{???}
\\providecommand{\\rqThreeSTSystemF}{???}
\\providecommand{\\rqThreeSTSystemFCI}{???}
\\providecommand{\\rqThreeSTSystemP}{???}
\\providecommand{\\rqThreeSTSystemR}{???}
% F1 improvement
\\providecommand{\\rqThreeSTDeltaF}{???}
\\providecommand{\\rqThreeSTDeltaFSys}{???}
""",
    "rq3_human_validation_table.tex": """\
% Placeholder - run reproduce_all_thesis_assets.py to generate
\\providecommand{\\rqThreeHumanValidationTradeoffTableBody}{%
\\begin{threeparttable}
\\begin{tabular}{lccc}
\\toprule
Metric & Value \\\\
\\midrule
\\textit{[Run reproduction scripts to generate]} & ??? \\\\
\\bottomrule
\\end{tabular}
\\end{threeparttable}
}
""",
    "node_ablation_stats.tex": """\
% Placeholder - run reproduce_all_thesis_assets.py to generate
\\item \\textit{[Stats: run reproduction scripts to generate]}
""",
}

# Directories to exclude from scanning
EXCLUDE_DIRS = {
    "__pycache__",
    ".git",
    "backup",
    "Data",  # Don't touch raw data
    "results",  # Don't touch raw results
    "data_science",  # Private timing data
}

# Files to exclude (keep these as-is)
EXCLUDE_FILES = {
    "README.md",
    "pyproject.toml",
    ".gitignore",
}

# Static figures that should NOT be reset (not generated by scripts, require private data)
STATIC_FIGURES = {
    # Title/intro images
    "CLD_thesis_intro_image.png",
    "CLD_thesis_intro_image_cropped.png",
    "CLD_thesis_intro_vignette.png",
    # Background chapter images
    "transformer_architecture.png",
    "transformer_Vaswani.png",
    # Pipeline diagrams
    "cld_pipeline_standalone_render.png",
    # Stanford cheatsheet images (in background_LLM_images_stanford_CME_Cheatsheet/)
    "attention_1_sequence.png",
    "attention_2_MHA.png",
    "architecture_1_encoder_decoder_example.png",
    "architecture_2_encoder_decoder_components.png",
    "decoding_sampling_2.png",
    "optimizations_1_attention.png",
    "token_1_seq.png",
    "variants_2_decoder_only.png",
    # Other static figures
    "transformer_architecture_orig.png",
    # Figures requiring data not in this repo (can't be regenerated)
    "edge_ablation_f1_ordered.png",  # No analysis script preserved
}


def should_exclude(path: Path) -> bool:
    """Check if path should be excluded."""
    for part in path.parts:
        if part in EXCLUDE_DIRS:
            return True
        # Exclude timestamped validation output directories
        if part.startswith("validation_unified_output_"):
            return True
    if path.name in EXCLUDE_FILES:
        return True
    return False


def find_tex_tables(base_dir: Path) -> list:
    """Find all .tex table files that should be reset."""
    tables = []
    for tex_file in base_dir.rglob("*.tex"):
        if should_exclude(tex_file):
            continue
        # Check if it's a table (not a main document)
        if tex_file.name in ["main.tex", "appendix_sensitivity.tex"]:
            continue
        # Check if it's a "numbers" file (defines LaTeX commands for inline use)
        if tex_file.name in NUMBERS_PLACEHOLDERS:
            tables.append(tex_file)
            continue
        # Check if it looks like a generated table
        content = tex_file.read_text(errors='ignore')
        if "\\begin{table}" in content or "\\begin{tabular}" in content or "Placeholder" in content:
            tables.append(tex_file)
    return tables


def find_generated_figures(base_dir: Path) -> list:
    """Find all generated PNG figures."""
    figures = []
    for png_file in base_dir.rglob("*.png"):
        if should_exclude(png_file):
            continue
        # Skip static assets that shouldn't be regenerated
        if png_file.name in STATIC_FIGURES:
            continue
        if "static" in str(png_file):
            continue
        figures.append(png_file)
    return figures


def reset_tables(tables: list, dry_run: bool = False):
    """Reset tables to placeholders."""
    print(f"\n=== Resetting {len(tables)} Tables ===")
    for table in sorted(tables):
        rel_path = table.relative_to(REPO_ROOT)
        # Check if this is a "numbers" file with special placeholder
        placeholder = NUMBERS_PLACEHOLDERS.get(table.name, PLACEHOLDER_TABLE)
        if dry_run:
            print(f"  [DRY-RUN] Would reset: {rel_path}")
        else:
            table.write_text(placeholder)
            print(f"  ✓ {rel_path}")


def reset_figures(figures: list, dry_run: bool = False):
    """Replace generated figures with placeholder image."""
    print(f"\n=== Resetting {len(figures)} Figures ===")
    
    placeholder_path = REPO_ROOT / "placeholders" / "placeholder_figure.png"
    if not placeholder_path.exists():
        print(f"  ⚠️ Placeholder image not found: {placeholder_path}")
        print("  (Figures will be overwritten on reproduction)")
        return
    
    count = 0
    for fig in sorted(figures):
        rel_path = fig.relative_to(REPO_ROOT)
        if dry_run:
            print(f"  [DRY-RUN] Would replace: {rel_path}")
        else:
            shutil.copy(placeholder_path, fig)
            count += 1
    
    if not dry_run:
        print(f"  Replaced {count} figures with placeholder")


def main():
    parser = argparse.ArgumentParser(description="Reset generated files to placeholders")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be reset without making changes")
    args = parser.parse_args()

    print("="*70)
    print("RESET TO PLACEHOLDERS")
    print("="*70)
    
    if args.dry_run:
        print("\n*** DRY RUN - No changes will be made ***\n")
    else:
        print("\nThis will overwrite generated tables with placeholder content.")
        print("Run 'python3 final_runs/reproduce_all_thesis_assets.py' to regenerate.\n")

    # Find all tables in final_runs
    final_runs_tables = find_tex_tables(FINAL_RUNS)
    
    # Find tables in thesis/reproducible_version/generated
    thesis_tables = list(THESIS_GENERATED.glob("*.tex")) if THESIS_GENERATED.exists() else []
    
    # Find tables in thesis/reproducible_version/Figures/generated
    thesis_figures_tables = list(THESIS_FIGURES_GENERATED.glob("*.tex")) if THESIS_FIGURES_GENERATED.exists() else []
    
    # Find generated figures in both locations
    figures_final_runs = find_generated_figures(FINAL_RUNS)
    figures_thesis = find_generated_figures(THESIS_FIGURES) if THESIS_FIGURES.exists() else []
    figures = figures_final_runs + figures_thesis

    # Report
    print(f"\nFound:")
    print(f"  - {len(final_runs_tables)} tables in final_runs/")
    print(f"  - {len(thesis_tables)} tables in thesis/reproducible_version/generated/")
    print(f"  - {len(thesis_figures_tables)} tables in thesis/reproducible_version/Figures/generated/")
    print(f"  - {len(figures_final_runs)} figures in final_runs/")
    print(f"  - {len(figures_thesis)} figures in thesis/reproducible_version/Figures/")

    # Reset tables
    all_tables = final_runs_tables + thesis_tables + thesis_figures_tables
    reset_tables(all_tables, dry_run=args.dry_run)
    
    # Reset figures
    reset_figures(figures, dry_run=args.dry_run)

    print("\n" + "="*70)
    if args.dry_run:
        print("DRY RUN complete - no changes made")
        print("Run without --dry-run to apply changes")
    else:
        print("✅ Reset complete!")
    print("="*70)
    print("\nTo regenerate all content:")
    print("  python3 final_runs/reproduce_all_thesis_assets.py")
    print("\nOr use Docker:")
    print("  docker build -t thesis-repro . && docker run -v $(pwd)/output:/output thesis-repro")


if __name__ == "__main__":
    main()
