#!/usr/bin/env python3
"""
Generate the thesis Table 21: Computational Efficiency Summary by Experiment.

Sources:
- RQ1a + RQ1b: `final_runs/cost_analysis/cost_complete_results.json`
  (generated by `calculate_all_costs.py`)
- RQ3 Deep Research: `final_runs/cost_analysis/dr_cost_analysis_latest.json`
  (generated by `compute_dr_costs.py`)

Output:
- `final_runs/latex/table21_scaling_summary.tex`
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Any, List


def _fmt_int(n: float | int) -> str:
    return f"{int(round(n)):,}"


def _fmt_money(n: float) -> str:
    return f"{n:,.2f}"


def _short_model(model: str) -> str:
    m = (model or "").lower()
    if "gpt-5-mini" in m or "5-mini" in m or "gpt-4o-mini" in m:
        return "5m"
    if "gpt-4.1" in m or "4.1" in m:
        return "4.1"
    if "gpt-5" in m:
        return "5"
    return model


def _by_experiment(rows: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    return {r["Experiment"]: r for r in rows}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate thesis Table 21 (scaling summary).")
    parser.add_argument(
        "--repo-root",
        type=str,
        default=str(Path(__file__).resolve().parents[2]),
        help="Path to repo root (default: inferred from script location).",
    )
    args = parser.parse_args()

    repo_root = Path(args.repo_root)
    cost_json_path = repo_root / "final_runs" / "cost_analysis" / "cost_complete_results.json"
    dr_json_path = repo_root / "final_runs" / "cost_analysis" / "dr_cost_analysis_latest.json"
    out_path = repo_root / "final_runs" / "latex" / "table21_scaling_summary.tex"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if not cost_json_path.exists():
        raise FileNotFoundError(
            f"Missing {cost_json_path}. Run: python3 final_runs/cost_analysis/calculate_all_costs.py"
        )
    if not dr_json_path.exists():
        raise FileNotFoundError(
            f"Missing {dr_json_path}. Run: python3 final_runs/cost_analysis/compute_dr_costs.py"
        )

    cost_data = json.loads(cost_json_path.read_text())
    rq1a = _by_experiment(cost_data.get("rq1a", []))
    rq1b = _by_experiment(cost_data.get("rq1b", []))

    dr_data = json.loads(dr_json_path.read_text())
    dr_agg = dr_data["aggregate"]["costs"]
    dr_files = len(dr_data.get("per_cld", {}) or {})

    # Build rows in the exact thesis order
    rq1a_order = [
        "RQ1a Corruption Citation",
        "RQ1a Ground Truth Citation",
        "RQ1a Corruption Correctness",
        "RQ1a Ground Truth Correctness",
        "RQ1a Human Validation",
    ]
    rq1b_order = [
        "RQ1b Synth Baseline",
        "RQ1b Synth CoT",
        "RQ1b Synth Mechanistic",
        "RQ1b GT Baseline",
        "RQ1b GT CoT",
        "RQ1b GT Mechanistic",
    ]

    lines: List[str] = []
    lines.append(r"\begin{table}[H]")
    lines.append(r"\centering")
    lines.append(r"\caption{Computational Efficiency Summary by Experiment}")
    lines.append(r"\label{tab:scaling_summary}")
    lines.append(r"\footnotesize")
    lines.append(r"\begin{tabular}{llccccc}")
    lines.append(r"\toprule")
    lines.append(r"\textbf{Experiment} & \textbf{Model} & \textbf{Files} & \textbf{Edges} & \textbf{Tok/Edge} & \textbf{¢/Edge} & \textbf{Total (\$)} \\")
    lines.append(r"\midrule")

    lines.append(r"\multicolumn{7}{l}{\textit{RQ1a Judge Experiments (actual)}} \\")
    for k in rq1a_order:
        r = rq1a.get(k)
        if not r:
            continue
        exp = k.replace("RQ1a ", "")
        lines.append(
            f"{exp} & {_short_model(r['Model'])} & {r['Files']} & {_fmt_int(r['Edges'])} & "
            f"{_fmt_int(r['Tokens/Edge'])} & {r['Cost/Edge (¢)']:.2f} & {_fmt_money(r['Total Cost ($)'])} \\\\"
        )

    lines.append(r"\midrule")
    lines.append(r"\multicolumn{7}{l}{\textit{RQ1b Corrector Experiments (estimated)}} \\")
    for k in rq1b_order:
        r = rq1b.get(k)
        if not r:
            continue
        exp = k.replace("RQ1b ", "")
        lines.append(
            f"{exp} & {_short_model(r['Model'])} & {r['Files']} & {_fmt_int(r['Edges'])} & "
            f"{_fmt_int(r['Tokens/Edge'])} & {r['Cost/Edge (¢)']:.2f} & {_fmt_money(r['Total Cost ($)'])} \\\\"
        )

    lines.append(r"\midrule")
    lines.append(r"\multicolumn{7}{l}{\textit{RQ3 Deep Research (actual)}} \\")
    dr_cost_per_edge_cents = float(dr_agg["cost_per_edge"]) * 100.0
    lines.append(
        f"Deep Research & 5/5m & {dr_files} & {_fmt_int(dr_agg['edges'])} & {_fmt_int(dr_agg['tokens_per_edge'])} & "
        f"{dr_cost_per_edge_cents:.2f} & {_fmt_money(float(dr_agg['total_cost']))} \\\\"
    )

    total_cost = float(cost_data.get("grand_total", 0.0)) + float(dr_agg["total_cost"])
    lines.append(r"\midrule")
    lines.append(f"\\textbf{{Total}} & & & & & & \\textbf{{{_fmt_money(total_cost)}}} \\\\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\begin{tablenotes}")
    lines.append(r"\small")
    lines.append(r"\item \textit{Note.} RQ1a costs from actual LLM Usage Stats. RQ1b estimated: correction + rejudging = 2$\times$ correctness tokens/edge. RQ3 from Deep Research logs.")
    lines.append(r"\item \textit{Reproduction:} \texttt{python3 final\_runs/cost\_analysis/calculate\_all\_costs.py}, \texttt{python3 final\_runs/cost\_analysis/compute\_dr\_costs.py}")
    lines.append(r"\end{tablenotes}")
    lines.append(r"\end{table}")

    out_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())














