#!/usr/bin/env python3
"""
Analyze Human Validation Results: LLM Judge vs Expert Agreement

Generates:
- human_validation_table.tex: Inter-rater agreement by dataset
- human_validation_confusion_table.tex: Confusion matrix of disagreements

Data source: combined_human_validation_results.xlsx
"""

import argparse
from pathlib import Path
import pandas as pd
import numpy as np
from scipy import stats


def compute_cohens_kappa(y1: np.ndarray, y2: np.ndarray) -> float:
    """Compute Cohen's Kappa for ordinal data."""
    # Get unique categories
    categories = sorted(set(y1) | set(y2))
    n = len(y1)
    
    # Build confusion matrix
    k = len(categories)
    matrix = np.zeros((k, k))
    cat_to_idx = {c: i for i, c in enumerate(categories)}
    
    for a, b in zip(y1, y2):
        matrix[cat_to_idx[a], cat_to_idx[b]] += 1
    
    # Compute observed agreement
    p_o = np.trace(matrix) / n
    
    # Compute expected agreement
    row_sums = matrix.sum(axis=1)
    col_sums = matrix.sum(axis=0)
    p_e = np.sum(row_sums * col_sums) / (n * n)
    
    # Cohen's Kappa
    if p_e == 1:
        return 1.0
    kappa = (p_o - p_e) / (1 - p_e)
    return kappa


def analyze_by_source(df: pd.DataFrame) -> list:
    """Analyze each source file separately."""
    results = []
    
    source_info = {
        'File1_MIck_1': ('File 1 (Depressive Symptoms)', 'GPT-4.1'),
        'File2_Claude4Sonnet': ('File 2 (Depressive Symptoms)', 'Claude 4 Sonnet'),
        'File3_ResultExcel': ('File 3 (Social Norms)', 'GPT-4.1'),
    }
    
    for source in df['Source'].unique():
        subset = df[df['Source'] == source]
        n = len(subset)
        
        llm_scores = subset['LLM_Score'].values
        human_scores = subset['Human_Score'].values
        
        # Cohen's Kappa
        kappa = compute_cohens_kappa(llm_scores, human_scores)
        
        # Agreement (exact match)
        agreement = (llm_scores == human_scores).mean() * 100
        
        # Pearson correlation
        if np.std(llm_scores) > 0 and np.std(human_scores) > 0:
            r, p_value = stats.pearsonr(llm_scores, human_scores)
            if p_value < 0.001:
                r_str = f"{r:.3f}***"
            elif p_value < 0.01:
                r_str = f"{r:.3f}**"
            elif p_value < 0.05:
                r_str = f"{r:.3f}*"
            else:
                r_str = f"{r:.3f}"
        else:
            r_str = "---"
        
        dataset, generator = source_info.get(source, (source, 'Unknown'))
        results.append({
            'dataset': dataset,
            'generator': generator,
            'n': n,
            'kappa': kappa,
            'agreement': agreement,
            'pearson_r': r_str
        })
    
    return results


def compute_confusion(df: pd.DataFrame) -> dict:
    """Compute confusion matrix of disagreements."""
    confusion = {
        'LLM Fully, Human Partially': 0,
        'LLM Fully, Human Not': 0,
        'LLM Partially, Human Fully': 0,
        'LLM Partially, Human Not': 0,
        'LLM Not, Human Fully': 0,
        'LLM Not, Human Partially': 0,
    }
    
    for _, row in df.iterrows():
        llm = row['LLM_Score']
        human = row['Human_Score']
        
        if llm == human:
            continue
        
        if llm == 1.0 and human == 0.5:
            confusion['LLM Fully, Human Partially'] += 1
        elif llm == 1.0 and human == 0.0:
            confusion['LLM Fully, Human Not'] += 1
        elif llm == 0.5 and human == 1.0:
            confusion['LLM Partially, Human Fully'] += 1
        elif llm == 0.5 and human == 0.0:
            confusion['LLM Partially, Human Not'] += 1
        elif llm == 0.0 and human == 1.0:
            confusion['LLM Not, Human Fully'] += 1
        elif llm == 0.0 and human == 0.5:
            confusion['LLM Not, Human Partially'] += 1
    
    return confusion


def generate_table1(results: list, combined_stats: dict, output_path: Path):
    """Generate human_validation_table.tex"""
    lines = [
        "% Table: Human Validation - LLM Judge vs Expert Inter-Rater Agreement",
        "% Generated by: final_runs/validation_RQ1a_human_agreement/analysis_scripts/analyze_human_validation.py",
        "% Data source: Excel files from human validation with domain expert (Mick)",
        r"\begin{table}[H]",
        r"\centering",
        r"\caption{Human Validation: LLM Judge vs.\ Expert Inter-Rater Agreement}",
        r"\label{tab:human_validation}",
        r"\begin{threeparttable}",
        r"\begin{tabular}{llcccc}",
        r"\toprule",
        r"\textbf{Dataset} & \textbf{Generator} & \textbf{n} & \textbf{Cohen's $\kappa$} & \textbf{Agreement} & \textbf{Pearson $r$} \\",
        r"\midrule",
    ]
    
    for r in results:
        lines.append(
            f"{r['dataset']} & {r['generator']} & {r['n']} & "
            f"{r['kappa']:.3f} & {r['agreement']:.1f}\\% & {r['pearson_r']} \\\\"
        )
    
    lines.extend([
        r"\midrule",
        f"\\textbf{{Combined}} & \\textbf{{2 models}} & \\textbf{{{combined_stats['n']}}} & "
        f"\\textbf{{{combined_stats['kappa']:.3f}}} & \\textbf{{{combined_stats['agreement']:.1f}\\%}} & "
        f"\\textbf{{{combined_stats['pearson_r']}}} \\\\",
        r"\midrule",
        r"Human baseline & N/A (expert) & 13 & $\sim$0.60 & 80.0\% & --- \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\begin{tablenotes}",
        r"\small",
        r"\item \textit{Note.} Inter-rater reliability between LLM citation judge (GPT-4.1, temp=0.0) and domain expert.",
        r"\item Verdicts: Not supported (0), Partially supported (0.5), Fully supported (1).",
        r"\item $\kappa$ interpretation \cite{landis1977measurement}: $<$0.20 slight, 0.21--0.40 fair, 0.41--0.60 moderate, 0.61--0.80 substantial, $>$0.80 almost perfect.",
        r"\item Human baseline from prior GMB validation studies on comparable expert tasks.",
        r"\item Significance: ** $p<0.01$, *** $p<0.001$.",
        r"\end{tablenotes}",
        r"\end{threeparttable}",
        r"\end{table}",
    ])
    
    output_path.write_text('\n'.join(lines) + '\n')
    print(f"Generated: {output_path}")


def generate_table2(df: pd.DataFrame, output_path: Path):
    """Generate human_validation_confusion_table.tex - proper 3x3 confusion matrix"""
    total_n = len(df)
    
    # Build 3x3 confusion matrix: rows = Human, columns = LLM
    # Categories: 0.0 = Not supported, 0.5 = Partially, 1.0 = Fully
    categories = [0.0, 0.5, 1.0]
    cat_labels = {0.0: "Not supported", 0.5: "Partially", 1.0: "Fully"}
    
    matrix = np.zeros((3, 3), dtype=int)
    for _, row in df.iterrows():
        human_idx = categories.index(row['Human_Score'])
        llm_idx = categories.index(row['LLM_Score'])
        matrix[human_idx, llm_idx] += 1
    
    lines = [
        "% Table: Human Validation - Confusion Matrix: LLM Judge vs Human Expert",
        "% Generated by: final_runs/validation_RQ1a_human_agreement/analysis_scripts/analyze_human_validation.py",
        r"\begin{table}[H]",
        r"\centering",
        f"\\caption{{Confusion Matrix: LLM Judge vs.\\ Human Expert (Combined, n={total_n})}}",
        r"\label{tab:human_validation_confusion}",
        r"\begin{threeparttable}",
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r" & \textbf{LLM: Not supported} & \textbf{LLM: Partially} & \textbf{LLM: Fully} \\",
        r"\midrule",
    ]
    
    row_labels = ["Human: Not supported", "Human: Partially", "Human: Fully"]
    for i, row_label in enumerate(row_labels):
        cells = []
        for j in range(3):
            count = matrix[i, j]
            pct = count / total_n * 100
            cells.append(f"{count} ({pct:.1f}\\%)")
        lines.append(f"\\textbf{{{row_label}}} & {cells[0]} & {cells[1]} & {cells[2]} \\\\")
    
    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        r"\begin{tablenotes}",
        r"\small",
        r"\item \textit{Note.} Rows = human expert verdicts; columns = LLM judge verdicts.",
        r"\end{tablenotes}",
        r"\end{threeparttable}",
        r"\end{table}",
    ])
    
    output_path.write_text('\n'.join(lines) + '\n')
    print(f"Generated: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Analyze human validation results")
    parser.add_argument("--output", type=str, help="Output directory for tables")
    parser.add_argument("--confusion-output", type=str, help="Output path for confusion table")
    args = parser.parse_args()
    
    script_dir = Path(__file__).parent
    data_dir = script_dir.parent / "Data"
    
    # Load data
    xlsx_path = data_dir / "combined_human_validation_results.xlsx"
    if not xlsx_path.exists():
        raise FileNotFoundError(f"Data file not found: {xlsx_path}")
    
    df = pd.read_excel(xlsx_path, engine='openpyxl')
    print(f"Loaded {len(df)} rows from {xlsx_path}")
    
    # Analyze by source
    results = analyze_by_source(df)
    
    # Compute combined stats
    llm_scores = df['LLM_Score'].values
    human_scores = df['Human_Score'].values
    combined_kappa = compute_cohens_kappa(llm_scores, human_scores)
    combined_agreement = (llm_scores == human_scores).mean() * 100
    r, p_value = stats.pearsonr(llm_scores, human_scores)
    if p_value < 0.001:
        combined_r_str = f"{r:.3f}***"
    elif p_value < 0.01:
        combined_r_str = f"{r:.3f}**"
    else:
        combined_r_str = f"{r:.3f}"
    
    combined_stats = {
        'n': len(df),
        'kappa': combined_kappa,
        'agreement': combined_agreement,
        'pearson_r': combined_r_str
    }
    
    print(f"\nResults by source:")
    for r in results:
        print(f"  {r['dataset']}: n={r['n']}, κ={r['kappa']:.3f}, agreement={r['agreement']:.1f}%")
    print(f"\nCombined: n={combined_stats['n']}, κ={combined_stats['kappa']:.3f}, agreement={combined_stats['agreement']:.1f}%")
    
    # Compute confusion matrix
    confusion = compute_confusion(df)
    total_disagreements = sum(confusion.values())
    print(f"\nDisagreements: {total_disagreements} ({total_disagreements/len(df)*100:.1f}%)")
    for k, v in confusion.items():
        if v > 0:
            print(f"  {k}: {v}")
    
    # Generate tables
    if args.output:
        output_path = Path(args.output)
    else:
        output_path = script_dir.parent / "human_validation_table.tex"
    
    if args.confusion_output:
        confusion_output_path = Path(args.confusion_output)
    else:
        confusion_output_path = script_dir.parent / "human_validation_confusion_table.tex"
    
    generate_table1(results, combined_stats, output_path)
    generate_table2(df, confusion_output_path)
    
    print("\nDone!")


if __name__ == "__main__":
    main()

