#!/usr/bin/env python3
"""Compute enriched Precision/Recall/F1 using human-validated enrichment extrapolation.

This script ties together:
- Full DR run outputs (TP/FP/FN counts; direct_causal_found counts)
- Human validation-derived enrichment estimates (from enrichment_extrapolation.py)

It computes:
1) Original (LLM vs expert GT) metrics
2) Enriched ground truth metrics (promote some FPs to TP)
3) LLM+DR system metrics (also discover some FNs)

By default it uses the *selected threshold* saved by `enrichment_extrapolation.py`.

Outputs:
- Prints a thesis-friendly summary
- Writes a JSON file `enriched_f1_from_validation_*.json` in the validation folder
- Writes LaTeX artifacts for the thesis Results section:
  - `thesis/final_thesis/generated/rq3_enrichment_validation_numbers.tex` (macros)
  - `thesis/final_thesis/generated/rq3_enrichment_validation_table.tex` (table)
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import pandas as pd

BASE_DIR = Path(__file__).parent.parent
DATA_DIR = BASE_DIR / "Data"
VALIDATION_DIR = BASE_DIR / "validation"
REPO_ROOT = BASE_DIR.parent.parent  # .../causalix.ai
THESIS_GENERATED_DIR = REPO_ROOT / "thesis" / "final_thesis" / "generated"

DR_FILES = [
    DATA_DIR / "deep_research_results_depressive_symptoms_20251013_032002_84edges.json",
    DATA_DIR / "deep_research_results_social_norms_20251012_213641_17edges.json",
    DATA_DIR / "deep_research_results_older_persons_ALL_EDGES_184edges.json",
]


def compute_prf(tp: int, fp: int, fn: int) -> dict:
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
    return {
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "precision": precision,
        "recall": recall,
        "f1": f1,
    }


def fmt3(x: float) -> str:
    return f"{x:.3f}"


def write_latex_artifacts(
    *,
    threshold: float,
    fp_promote: int,
    fp_promote_c: int,
    fn_discover: int,
    fn_discover_c: int,
    original: dict,
    enriched_gt: dict,
    enriched_gt_conservative: dict,
    system: dict,
    system_conservative: dict,
    out_dir: Path,
):
    out_dir.mkdir(parents=True, exist_ok=True)

    # 1) Numbers as macros for reproducible in-text references
    numbers_path = out_dir / "rq3_enrichment_validation_numbers.tex"
    numbers_tex = "\n".join(
        [
            "% Auto-generated by compute_enriched_f1_from_validation.py",
            f"\\newcommand{{\\rqThreeValThresh}}{{{threshold:.1f}}}",
            f"\\newcommand{{\\rqThreeFpPromote}}{{{fp_promote}}}",
            f"\\newcommand{{\\rqThreeFpPromoteCons}}{{{fp_promote_c}}}",
            f"\\newcommand{{\\rqThreeFnDiscover}}{{{fn_discover}}}",
            f"\\newcommand{{\\rqThreeFnDiscoverCons}}{{{fn_discover_c}}}",
            f"\\newcommand{{\\rqThreeFOne}}{{{fmt3(original['f1'])}}}",
            f"\\newcommand{{\\rqThreeFEnrich}}{{{fmt3(enriched_gt['f1'])}}}",
            f"\\newcommand{{\\rqThreeFEnrichCons}}{{{fmt3(enriched_gt_conservative['f1'])}}}",
            f"\\newcommand{{\\rqThreeFSystem}}{{{fmt3(system['f1'])}}}",
            f"\\newcommand{{\\rqThreeFSystemCons}}{{{fmt3(system_conservative['f1'])}}}",
            f"\\newcommand{{\\rqThreePrecOne}}{{{fmt3(original['precision'])}}}",
            f"\\newcommand{{\\rqThreeRecOne}}{{{fmt3(original['recall'])}}}",
            f"\\newcommand{{\\rqThreePrecEnrich}}{{{fmt3(enriched_gt['precision'])}}}",
            f"\\newcommand{{\\rqThreeRecEnrich}}{{{fmt3(enriched_gt['recall'])}}}",
            f"\\newcommand{{\\rqThreePrecSystem}}{{{fmt3(system['precision'])}}}",
            f"\\newcommand{{\\rqThreeRecSystem}}{{{fmt3(system['recall'])}}}",
            "",
        ]
    )
    numbers_path.write_text(numbers_tex)

    # 2) LaTeX table (full environment so Results can \\input it directly)
    table_path = out_dir / "rq3_enrichment_validation_table.tex"
    table_tex = "\n".join(
        [
            "% Auto-generated by compute_enriched_f1_from_validation.py",
            "\\begin{table}[H]",
            "\\centering",
            "\\caption{LLM Generation Metrics with Human-Validated Ground Truth Enrichment (Aggregate, extrapolated)}",
            "\\label{tab:enriched_gt_validated}",
            "\\begin{threeparttable}",
            "\\footnotesize",
            "\\begin{tabular}{lccc}",
            "\\toprule",
            "\\textbf{Scenario} & \\textbf{Precision} & \\textbf{Recall} & \\textbf{F1} \\\\",
            "\\midrule",
            f"Original (expert GT) & {fmt3(original['precision'])} & {fmt3(original['recall'])} & {fmt3(original['f1'])} \\\\",
            f"Scenario 1: Enriched GT (FP$\\to$TP) & {fmt3(enriched_gt['precision'])} & {fmt3(enriched_gt['recall'])} & {fmt3(enriched_gt['f1'])} \\\\",
            f"Scenario 2: LLM+DR System (+FN found) & {fmt3(system['precision'])} & {fmt3(system['recall'])} & {fmt3(system['f1'])} \\\\",
            "\\midrule",
            f"Conservative Scenario 1 & {fmt3(enriched_gt_conservative['precision'])} & {fmt3(enriched_gt_conservative['recall'])} & {fmt3(enriched_gt_conservative['f1'])} \\\\",
            f"Conservative Scenario 2 & {fmt3(system_conservative['precision'])} & {fmt3(system_conservative['recall'])} & {fmt3(system_conservative['f1'])} \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\begin{tablenotes}",
            "\\small",
            "\\item Threshold selected by elbow/gradient rule (Option B) on validation tradeoff curve: $t=\\rqThreeValThresh$.",
            "FP promotions (point / conservative): $\\rqThreeFpPromote$ / $\\rqThreeFpPromoteCons$.",
            "FN discoveries (point / conservative): $\\rqThreeFnDiscover$ / $\\rqThreeFnDiscoverCons$.",
            "Counts are extrapolated from a stratified human-validation sample and should be interpreted as estimates.",
            "\\end{tablenotes}",
            "\\end{threeparttable}",
            "\\end{table}",
            "",
        ]
    )
    table_path.write_text(table_tex)

    return numbers_path, table_path


def load_dr_counts() -> dict:
    totals = {"TP": 0, "FP": 0, "FN": 0}
    direct = {"TP": 0, "FP": 0, "FN": 0}

    for path in DR_FILES:
        data = json.loads(path.read_text())
        for e in data["results"]:
            cls = e["classification"]
            totals[cls] += 1
            if bool(e.get("direct_causal_found", False)):
                direct[cls] += 1

    return {"totals": totals, "direct_causal_found_true": direct}


def latest_file(glob_pattern: str) -> Path:
    matches = sorted(VALIDATION_DIR.glob(glob_pattern))
    if not matches:
        raise FileNotFoundError(f"No files matching {glob_pattern} in {VALIDATION_DIR}")
    return matches[-1]


def load_selected_threshold() -> float:
    sel_path = latest_file("threshold_selection_*.json")
    sel = json.loads(sel_path.read_text())
    return float(sel["selected_threshold"])


def load_enrichment_estimates(threshold: float) -> dict:
    est_path = latest_file("enrichment_estimates_*.csv")
    df = pd.read_csv(est_path)

    out = {}
    for cls in ["FP", "FN"]:
        row = df[(df["classification"] == cls) & (df["threshold"] == threshold)]
        if row.empty:
            raise ValueError(f"No enrichment estimate for {cls} at threshold={threshold} in {est_path.name}")
        r = row.iloc[0]
        out[cls] = {
            "full_eligible": int(r["full_eligible"]),
            "est_promotions": int(r["est_promotions"]),
            "est_conservative": int(r["est_conservative"]),
            "sample_pass_rate": float(r["sample_pass_rate"]),
            "sample_causal_rate": float(r["sample_causal_rate"]),
            "sample_causal_ci_low": float(r["sample_causal_ci_low"]),
            "sample_causal_ci_high": float(r["sample_causal_ci_high"]),
        }
    return {
        "estimates_file": est_path.name,
        "threshold": threshold,
        "by_class": out,
    }


def main() -> None:
    dr_counts = load_dr_counts()
    threshold = load_selected_threshold()
    enrich = load_enrichment_estimates(threshold)

    orig_tp = dr_counts["totals"]["TP"]
    orig_fp = dr_counts["totals"]["FP"]
    orig_fn = dr_counts["totals"]["FN"]

    fp_promote = enrich["by_class"]["FP"]["est_promotions"]
    fn_discover = enrich["by_class"]["FN"]["est_promotions"]

    fp_promote_c = enrich["by_class"]["FP"]["est_conservative"]
    fn_discover_c = enrich["by_class"]["FN"]["est_conservative"]

    # Scenario 0: original
    original = compute_prf(orig_tp, orig_fp, orig_fn)

    # Scenario 1: enriched GT (FP promotion)
    enriched_gt = compute_prf(orig_tp + fp_promote, orig_fp - fp_promote, orig_fn)
    enriched_gt_conservative = compute_prf(orig_tp + fp_promote_c, orig_fp - fp_promote_c, orig_fn)

    # Scenario 2: LLM+DR system (FP promotion + FN discovery)
    system = compute_prf(orig_tp + fp_promote + fn_discover, orig_fp - fp_promote, orig_fn - fn_discover)
    system_conservative = compute_prf(orig_tp + fp_promote_c + fn_discover_c, orig_fp - fp_promote_c, orig_fn - fn_discover_c)

    result = {
        "timestamp": datetime.now().isoformat(),
        "threshold": threshold,
        "dr_counts": dr_counts,
        "enrichment_inputs": enrich,
        "scenarios": {
            "original": original,
            "enriched_gt": enriched_gt,
            "enriched_gt_conservative": enriched_gt_conservative,
            "llm_plus_dr_system": system,
            "llm_plus_dr_system_conservative": system_conservative,
        },
        "deltas": {
            "enriched_gt_f1_delta": enriched_gt["f1"] - original["f1"],
            "system_f1_delta": system["f1"] - original["f1"],
        },
    }

    # Print thesis-friendly summary
    print("=" * 80)
    print("ENRICHED F1 FROM HUMAN-VALIDATED EXTRAPOLATION")
    print("=" * 80)
    print(f"Threshold: {threshold}")
    print(f"Using estimates from: {enrich['estimates_file']}")
    print("\nOriginal (LLM vs expert GT):")
    print(f"  TP={original['tp']} FP={original['fp']} FN={original['fn']}")
    print(f"  Precision={original['precision']:.3f} Recall={original['recall']:.3f} F1={original['f1']:.3f}")

    print("\nEnriched GT (promote FPs that pass validation):")
    print(f"  FP promotions (point): {fp_promote}   (conservative): {fp_promote_c}")
    print(f"  Precision={enriched_gt['precision']:.3f} Recall={enriched_gt['recall']:.3f} F1={enriched_gt['f1']:.3f}")
    print(f"  Conservative F1={enriched_gt_conservative['f1']:.3f}")

    print("\nLLM+DR system (also discover FNs that pass validation):")
    print(f"  FN discoveries (point): {fn_discover}  (conservative): {fn_discover_c}")
    print(f"  Precision={system['precision']:.3f} Recall={system['recall']:.3f} F1={system['f1']:.3f}")
    print(f"  Conservative F1={system_conservative['f1']:.3f}")

    # Save JSON
    out_path = VALIDATION_DIR / f"enriched_f1_from_validation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    out_path.write_text(json.dumps(result, indent=2))
    print(f"\nSaved: {out_path}")

    # Write LaTeX artifacts for thesis reproducibility
    numbers_path, table_path = write_latex_artifacts(
        threshold=threshold,
        fp_promote=fp_promote,
        fp_promote_c=fp_promote_c,
        fn_discover=fn_discover,
        fn_discover_c=fn_discover_c,
        original=original,
        enriched_gt=enriched_gt,
        enriched_gt_conservative=enriched_gt_conservative,
        system=system,
        system_conservative=system_conservative,
        out_dir=THESIS_GENERATED_DIR,
    )
    print(f"Saved LaTeX numbers: {numbers_path}")
    print(f"Saved LaTeX table:   {table_path}")


if __name__ == "__main__":
    main()
