#!/usr/bin/env python3
"""
Generate Search Provider Comparison Table from citation_fetcher_comparison xlsx.

Generates: search_provider_comparison_table.tex
"""

import argparse
from pathlib import Path
import pandas as pd


def generate_latex_table(df: pd.DataFrame, output_path: Path):
    """Generate LaTeX table from summary comparison dataframe."""
    lines = [
        "% Table: Search Provider Comparison on Uleman's Expert CLD",
        "% Generated by: final_runs/validation_RQ1a_ulemans_external/analysis_scripts/generate_search_provider_table.py",
        r"\begin{table}[H]",
        r"\centering",
        r"\caption{Search Provider Comparison on Uleman's Expert CLD (150 edges)}",
        r"\label{tab:ulemans_search_providers}",
        r"\begingroup",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\renewcommand{\arraystretch}{1.05}",
        r"\begin{threeparttable}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        r"\textbf{Provider} & \textbf{Jina AI} & \textbf{ContentScraper} & \textbf{Jina Edges} & \textbf{CS Edges} & \textbf{Jina} & \textbf{CS} \\",
        r" & \textbf{Avg Score} & \textbf{Avg Score} & \textbf{w/ Citations} & \textbf{w/ Citations} & \textbf{Coverage} & \textbf{Coverage} \\",
        r"\midrule",
    ]
    
    for _, row in df.iterrows():
        provider = row['Provider']
        # Clean up provider names
        if 'No whitelist' in str(provider) or 'no whitelist' in str(provider):
            provider = "Brave (no whitelist)"
        elif 'whitelist' in str(provider).lower() and 'no' not in str(provider).lower():
            provider = "Brave (whitelist)"
        
        jina_score = f"{row['Jina AI Avg Score']:.3f}"
        cs_score = f"{row['ContentScraper Avg Score']:.3f}"
        jina_edges = row['Jina AI Edges w/ Citations']
        cs_edges = row['ContentScraper Edges w/ Citations']
        jina_cov = str(row['Jina AI Coverage %']).replace('%', r'\%')
        cs_cov = str(row['ContentScraper Coverage %']).replace('%', r'\%')
        
        lines.append(
            f"{provider} & {jina_score} & {cs_score} & {jina_edges} & {cs_edges} & {jina_cov} & {cs_cov} \\\\"
        )
    
    lines.extend([
        r"\bottomrule",
        r"\end{tabular}%",
        r"}",
        r"\begin{tablenotes}",
        r"\small",
        r"\item \textit{Note.} Jina AI Reader = paywall-bypassing document fetcher; ContentScraper = standard web scraper.",
        r"\item Coverage = percentage of edges with successfully fetched citation content.",
        r"\item Score Difference = ContentScraper Avg Score $-$ Jina AI Avg Score.",
        r"\end{tablenotes}",
        r"\end{threeparttable}",
        r"\endgroup",
        r"\end{table}",
    ])
    
    output_path.write_text('\n'.join(lines) + '\n')
    print(f"Generated: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Generate search provider comparison table")
    parser.add_argument("--output", type=str, help="Output path for LaTeX table")
    args = parser.parse_args()
    
    script_dir = Path(__file__).parent
    project_root = script_dir.parent.parent.parent
    
    # Find the xlsx file
    xlsx_path = project_root / "final_runs" / "RQ1a_ulemans_citation_provider_comparison" / "citation_fetcher_comparison_20251113_v2.xlsx"
    
    if not xlsx_path.exists():
        print(f"Error: Data file not found: {xlsx_path}")
        return 1
    
    # Load summary comparison sheet
    df = pd.read_excel(xlsx_path, sheet_name='Summary Comparison', engine='openpyxl')
    print(f"Loaded {len(df)} providers from {xlsx_path}")
    
    # Generate table
    if args.output:
        output_path = Path(args.output)
    else:
        output_path = script_dir.parent / "search_provider_comparison_table.tex"
    
    generate_latex_table(df, output_path)
    
    print("\nDone!")
    return 0


if __name__ == "__main__":
    exit(main())

